set nocompatible

" Enable pathogen
execute pathogen#infect()

" General vim config
runtime config/airline.vim
runtime config/backups.vim
runtime config/colors.vim
runtime config/cursors.vim
runtime config/copypasta.vim
runtime config/leader.vim
runtime config/options.vim
runtime config/keymaps.vim
runtime config/status.vim
runtime config/wp.vim

" Settings for specific languages
runtime config/langs/cpp.vim
runtime config/langs/go.vim
runtime config/langs/haskell.vim
runtime config/langs/html.vim
runtime config/langs/javascript.vim
runtime config/langs/json.vim
runtime config/langs/makefiles.vim
runtime config/langs/markdown.vim
runtime config/langs/python.vim
runtime config/langs/vue.vim
