format = """
$python\
$directory\
$git_branch\
$git_status\
$character
"""

# Don't print a newline at the start of the prompt
add_newline = false

# Don't let starship timeout long running commands (milliseconds)
command_timeout = 100000

[character]
success_symbol = "[ λ](grey)"
error_symbol = "[ λ](grey)"

[directory]
truncation_length = 1
truncation_symbol = "…/"
fish_style_pwd_dir_length = 1
style = "white"
format = "[$path]($style)[$read_only]($read_only_style)"

[git_branch]
format = "[ $branch](blue)"

[git_status]
deleted = 'x'
format = '[$modified](red)[$renamed](green)[$deleted](red)[$untracked](red)[$staged](green)[$stashed](red)[$ahead](green)[$behind](red)[$conflicted](red)[$diverged](red)'

# Don't show anything about python virtual envs for now
[python]
format = ''
#format = '[\($virtualenv\) ](green)'
